// Generates sql/02_seed.sql from the existing front-end catalogue so the
// database and the 3D shop can never drift apart at import time.
import { writeFileSync, readdirSync, existsSync } from 'fs';
import bcrypt from 'bcryptjs';
import { PRODUCTS, CATEGORIES } from '../src/products.js';

const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined ? 'NULL' : String(v));
const out = [];
const w = (s = '') => out.push(s);

w('-- ============================================================');
w('--  METAMART - seed data');
w('--  Generated by scripts/gen-seed.mjs - do not edit by hand.');
w('-- ============================================================');
w('SET NAMES utf8mb4;');
w('');

/* ---------------- architectures ---------------- */
// Three room blueprints. Capacity is what the physical room can display.
const ARCHS = [
  {
    code: 'l_hall', name: 'L-Hall Flagship',
    desc: 'Anchor store: main hall plus a wing, brand walls on three sides and a highlight island in the centre.',
    maxCat: 8, maxProd: 5, island: 1, cap: 4,
    layout: {
      regions: ['hall', 'wing'],
      categorySlots: [
        { slot: 0, wall: 'west',  label: 'Main hall west' },
        { slot: 1, wall: 'north', label: 'Main hall north' },
        { slot: 2, wall: 'east',  label: 'Main hall east' },
        { slot: 3, wall: 'wing_west',  label: 'Wing west' },
        { slot: 4, wall: 'wing_east',  label: 'Wing east' },
        { slot: 5, wall: 'wing_south', label: 'Wing south' },
        { slot: 6, wall: 'hall_south_a', label: 'Hall south A' },
        { slot: 7, wall: 'hall_south_b', label: 'Hall south B' },
      ],
    },
  },
  {
    code: 'boutique', name: 'Boutique Room',
    desc: 'Single square room, four display walls and a small centre plinth. For smaller tenants.',
    maxCat: 4, maxProd: 5, island: 1, cap: 3,
    layout: {
      regions: ['room'],
      categorySlots: [
        { slot: 0, wall: 'west',  label: 'West wall' },
        { slot: 1, wall: 'north', label: 'North wall' },
        { slot: 2, wall: 'east',  label: 'East wall' },
        { slot: 3, wall: 'south', label: 'South wall' },
      ],
    },
  },
  {
    code: 'gallery', name: 'Gallery Loft',
    desc: 'Long daylight gallery with six bays down two colonnades and an end-wall feature.',
    maxCat: 7, maxProd: 5, island: 0, cap: 0,
    layout: {
      regions: ['gallery'],
      categorySlots: [
        { slot: 0, wall: 'bay_w1', label: 'West bay 1' },
        { slot: 1, wall: 'bay_w2', label: 'West bay 2' },
        { slot: 2, wall: 'bay_w3', label: 'West bay 3' },
        { slot: 3, wall: 'bay_e1', label: 'East bay 1' },
        { slot: 4, wall: 'bay_e2', label: 'East bay 2' },
        { slot: 5, wall: 'bay_e3', label: 'East bay 3' },
        { slot: 6, wall: 'end',    label: 'End wall feature' },
      ],
    },
  },
];

w('-- ---------- architectures ----------');
ARCHS.forEach((a) => {
  w(`INSERT INTO architectures (code, name, description, max_categories, max_products_per_category, has_highlight_island, highlight_capacity, layout_json) VALUES`);
  w(`  (${q(a.code)}, ${q(a.name)}, ${q(a.desc)}, ${a.maxCat}, ${a.maxProd}, ${a.island}, ${a.cap}, ${q(JSON.stringify(a.layout))});`);
});
w('');

/* ---------------- spaces ---------------- */
// SoleSpace is the anchor (through the gate). The nine plaza bays are the
// tenants from src/concourse.js.
const TENANTS = [
  { slug: 'menswear',   name: "Men's Wear",       accent: '#4cc9f0', bay: 0, arch: 'gallery'  },
  { slug: 'womenswear', name: "Women's Wear",     accent: '#ff7ab6', bay: 1, arch: 'gallery'  },
  { slug: 'gadgets',    name: 'Gadgets',          accent: '#9b5de5', bay: 2, arch: 'boutique' },
  { slug: 'bags',       name: 'Bags & Luggage',   accent: '#c98b5e', bay: 3, arch: 'boutique' },
  { slug: 'sports',     name: 'Sports & Jerseys', accent: '#3ddc84', bay: 4, arch: 'gallery'  },
  { slug: 'watches',    name: 'Watches',          accent: '#ffd166', bay: 5, arch: 'boutique' },
  { slug: 'beauty',     name: 'Beauty',           accent: '#ff6a8a', bay: 6, arch: 'boutique' },
  { slug: 'kids',       name: 'Kids & Toys',      accent: '#ffa94d', bay: 7, arch: 'gallery'  },
  { slug: 'home',       name: 'Home & Living',    accent: '#2ec4b6', bay: 8, arch: 'boutique' },
];

w('-- ---------- spaces ----------');
w(`INSERT INTO spaces (slug, name, tagline, description, architecture_id, accent_color, bay_index, status, sort_order) VALUES`);
const spaceRows = [];
spaceRows.push(
  `  (${q('solespace')}, ${q('SoleSpace')}, ${q('Sneakers, curated.')}, ` +
  `${q('The anchor store of METAMART: six brand walls across a daylight hall and wing, plus a rotating highlight island.')}, ` +
  `(SELECT id FROM architectures WHERE code='l_hall'), ${q('#00e5ff')}, NULL, ${q('live')}, 0)`
);
TENANTS.forEach((t, i) => {
  spaceRows.push(
    `  (${q(t.slug)}, ${q(t.name)}, ${q('Opening soon on METAMART.')}, NULL, ` +
    `(SELECT id FROM architectures WHERE code=${q(t.arch)}), ${q(t.accent)}, ${t.bay}, ${q('coming_soon')}, ${i + 1})`
  );
});
w(spaceRows.join(',\n') + ';');
w('');

/* ---------------- categories ---------------- */
// The 'sale' pseudo-category from the front end becomes a highlight, not a
// category, so its products are filed under their real brands.
const BRAND_CATS = CATEGORIES.filter((c) => c.id !== 'sale');
w('-- ---------- categories (SoleSpace) ----------');
w(`INSERT INTO categories (space_id, slug, name, accent_color, slot_index, sort_order) VALUES`);
w(
  BRAND_CATS.map(
    (c, i) =>
      `  ((SELECT id FROM spaces WHERE slug='solespace'), ${q(c.id)}, ${q(c.name)}, ${q(c.accent)}, ${i}, ${i})`
  ).join(',\n') + ';'
);
w('');

/* ---------------- products ---------------- */
// Re-home the four sale products under their real brand.
const SALE_HOME = {
  'yeezy-foam-rnnr': 'adidas',
  'nb-530': 'newbalance',
  'gel-1130-black': 'asics',
  'nb-1906r': 'newbalance',
};
const SIZES = [40, 41, 42, 43, 44, 45];

const rows = PRODUCTS.map((p) => {
  const cat = p.category === 'sale' ? SALE_HOME[p.id] : p.category;
  if (!cat) throw new Error(`No home category for sale product ${p.id}`);
  return { ...p, cat };
});

// slot_index per category, and capacity check against the architecture
const perCat = {};
rows.forEach((r) => {
  perCat[r.cat] = perCat[r.cat] || [];
  r.slot = perCat[r.cat].length;
  perCat[r.cat].push(r.id);
});
const arch = ARCHS.find((a) => a.code === 'l_hall');
for (const [cat, ids] of Object.entries(perCat)) {
  if (ids.length > arch.maxProd) {
    throw new Error(`Category ${cat} has ${ids.length} products, max is ${arch.maxProd}: ${ids.join(', ')}`);
  }
}
if (BRAND_CATS.length > arch.maxCategories) {
  throw new Error(`Too many categories for ${arch.code}`);
}

w('-- ---------- products ----------');
w(
  `INSERT INTO products (space_id, category_id, sku, slug, name, brand, short_description, description, price_cents, currency, slot_index, status, badge, stock, attributes_json) VALUES`
);
w(
  rows
    .map((r) => {
      const brand = CATEGORIES.find((c) => c.id === r.cat)?.name ?? null;
      const sku = `SS-${r.cat.toUpperCase().slice(0, 3)}-${String(r.slot + 1).padStart(2, '0')}-${r.id.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 10)}`;
      const short = r.desc.length > 300 ? r.desc.slice(0, 297) + '...' : r.desc;
      const attrs = JSON.stringify({ source: 'seed', original_id: r.id });
      return (
        `  ((SELECT id FROM spaces WHERE slug='solespace'), ` +
        `(SELECT id FROM categories WHERE slug=${q(r.cat)} AND space_id=(SELECT id FROM spaces WHERE slug='solespace')), ` +
        `${q(sku)}, ${q(r.id)}, ${q(r.name)}, ${q(brand)}, ${q(short)}, ${q(r.desc)}, ` +
        `${Math.round(r.price * 100)}, 'USD', ${r.slot}, 'active', ${q(r.tag ?? null)}, ${20 + (r.slot * 7) % 40}, ${q(attrs)})`
      );
    })
    .join(',\n') + ';'
);
w('');

/* ---------------- images ---------------- */
w('-- ---------- product images ----------');
w(`INSERT INTO product_images (product_id, file_path, alt_text, sort_order, is_primary) VALUES`);
w(
  rows
    .map(
      (r) =>
        `  ((SELECT id FROM products WHERE slug=${q(r.id)} AND space_id=(SELECT id FROM spaces WHERE slug='solespace')), ` +
        `${q(r.img)}, ${q(r.name + ' product photo')}, 0, 1)`
    )
    .join(',\n') + ';'
);
w('');

/* ---------------- variants ---------------- */
w('-- ---------- product variants (EU sizes) ----------');
w(`INSERT INTO product_variants (product_id, size_label, size_system, stock, sort_order) VALUES`);
const varRows = [];
rows.forEach((r) => {
  SIZES.forEach((s, i) => {
    varRows.push(
      `  ((SELECT id FROM products WHERE slug=${q(r.id)} AND space_id=(SELECT id FROM spaces WHERE slug='solespace')), ` +
      `${q(String(s))}, 'EU', ${3 + ((s + i) % 9)}, ${i})`
    );
  });
});
w(varRows.join(',\n') + ';');
w('');

/* ---------------- tags ---------------- */
const TAG_SEED = [
  ['sneakers', 'Sneakers', 'style'], ['retro', 'Retro', 'style'], ['running', 'Running', 'use'],
  ['basketball', 'Basketball', 'use'], ['lifestyle', 'Lifestyle', 'use'], ['skate', 'Skate', 'use'],
  ['white', 'White', 'color'], ['black', 'Black', 'color'], ['grey', 'Grey', 'color'],
  ['leather', 'Leather', 'material'], ['canvas', 'Canvas', 'material'], ['mesh', 'Mesh', 'material'],
  ['knit', 'Knit', 'material'], ['suede', 'Suede', 'material'],
  ['unisex', 'Unisex', 'audience'], ['limited', 'Limited', 'other'], ['classic', 'Classic', 'other'],
];
w('-- ---------- tags ----------');
w(`INSERT INTO tags (slug, name, kind) VALUES`);
w(TAG_SEED.map((t) => `  (${q(t[0])}, ${q(t[1])}, ${q(t[2])})`).join(',\n') + ';');
w('');

// naive keyword tagging as a starting point; the AI enrich agent refines it
w('-- ---------- product tags (keyword pass; AI refines later) ----------');
const ptRows = [];
rows.forEach((r) => {
  const hay = `${r.name} ${r.desc}`.toLowerCase();
  const hits = new Set(['sneakers']);
  TAG_SEED.forEach(([slug]) => {
    if (slug !== 'sneakers' && hay.includes(slug)) hits.add(slug);
  });
  hits.forEach((slug) => {
    ptRows.push(
      `  ((SELECT id FROM products WHERE slug=${q(r.id)} AND space_id=(SELECT id FROM spaces WHERE slug='solespace')), ` +
      `(SELECT id FROM tags WHERE slug=${q(slug)}), 'human')`
    );
  });
});
w(`INSERT INTO product_tags (product_id, tag_id, source) VALUES`);
w(ptRows.join(',\n') + ';');
w('');

/* ---------------- highlights ---------------- */
w('-- ---------- highlights (centre island presets) ----------');
w(`INSERT INTO highlights (space_id, code, title, subtitle, accent_color, is_active, sort_order) VALUES`);
w(
  [
    `  ((SELECT id FROM spaces WHERE slug='solespace'), 'sale', ${q('SALE %')}, ${q('Marked down while stock lasts')}, ${q('#ff2d55')}, 1, 0)`,
    `  ((SELECT id FROM spaces WHERE slug='solespace'), 'popular', ${q('POPULAR')}, ${q('What everyone is buying')}, ${q('#ffd166')}, 0, 1)`,
    `  ((SELECT id FROM spaces WHERE slug='solespace'), 'new_arrival', ${q('NEW ARRIVALS')}, ${q('Fresh on the shelves')}, ${q('#3ddc84')}, 0, 2)`,
  ].join(',\n') + ';'
);
w('');

const SALE_IDS = Object.keys(SALE_HOME);
const POPULAR_IDS = ['dunk-panda', 'samba-og', 'aj4-military', 'nb-550'];
const NEW_IDS = ['gel-kayano-14', 'nb-2002r-rain', 'kobe-6-grinch', 'campus-00s'];
const hlItems = (code, ids) =>
  ids.map(
    (id, i) =>
      `  ((SELECT id FROM highlights WHERE code=${q(code)} AND space_id=(SELECT id FROM spaces WHERE slug='solespace')), ` +
      `(SELECT id FROM products WHERE slug=${q(id)} AND space_id=(SELECT id FROM spaces WHERE slug='solespace')), ${i})`
  );
w('-- ---------- highlight items ----------');
w(`INSERT INTO highlight_items (highlight_id, product_id, sort_order) VALUES`);
w([...hlItems('sale', SALE_IDS), ...hlItems('popular', POPULAR_IDS), ...hlItems('new_arrival', NEW_IDS)].join(',\n') + ';');
w('');

/* ---------------- discounts ---------------- */
// The four sale products keep their original markdown as a real discount row.
const SALE_PRICES = { 'yeezy-foam-rnnr': [90, 59], 'nb-530': [100, 69], 'gel-1130-black': [120, 79], 'nb-1906r': [155, 99] };
w('-- ---------- discounts ----------');
w(`INSERT INTO discounts (code, name, kind, value, scope, target_id, starts_at, ends_at, is_active, priority) VALUES`);
w(
  Object.entries(SALE_PRICES)
    .map(([slug, [was, now]]) => {
      const off = Math.round((was - now) * 100);
      return (
        `  (${q('SEED-' + slug.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 12))}, ${q('Launch markdown - ' + slug)}, 'fixed', ${off}, 'product', ` +
        `(SELECT id FROM products WHERE slug=${q(slug)} AND space_id=(SELECT id FROM spaces WHERE slug='solespace')), ` +
        `NOW(), DATE_ADD(NOW(), INTERVAL 90 DAY), 1, 10)`
      );
    })
    .join(',\n') + ';'
);
w('');

/* ---------------- search index ---------------- */
w('-- ---------- search index (text; embeddings filled by the AI worker) ----------');
w(`INSERT INTO product_search (product_id, content) VALUES`);
w(
  rows
    .map((r) => {
      const brand = CATEGORIES.find((c) => c.id === r.cat)?.name ?? '';
      const content = `${r.name} ${brand} ${r.cat} sneakers ${r.desc}`.replace(/\s+/g, ' ').trim();
      return (
        `  ((SELECT id FROM products WHERE slug=${q(r.id)} AND space_id=(SELECT id FROM spaces WHERE slug='solespace')), ${q(content)})`
      );
    })
    .join(',\n') + ';'
);
w('');

/* ---------------- admin + settings ---------------- */
const DEFAULT_PW = 'ChangeMe!2026';
const hash = bcrypt.hashSync(DEFAULT_PW, 10);
w('-- ---------- admin user ----------');
w(`-- Default login: admin@metamart.local  /  ${DEFAULT_PW}   <-- CHANGE THIS AFTER FIRST LOGIN`);
w(`INSERT INTO admin_users (email, password_hash, name, role) VALUES`);
w(`  (${q('admin@metamart.local')}, ${q(hash)}, ${q('Owner')}, 'owner');`);
w('');

w('-- ---------- settings ----------');
w(`INSERT INTO settings (k, v_json) VALUES`);
w(
  [
    `  ('mart.name', ${q(JSON.stringify('METAMART'))})`,
    `  ('mart.currency', ${q(JSON.stringify('USD'))})`,
    `  ('ai.provider_order', ${q(JSON.stringify(['groq', 'openai', 'gemini']))})`,
    `  ('ai.enabled_agents', ${q(JSON.stringify(['enrich', 'search', 'vision', 'merchandiser', 'stylist']))})`,
    `  ('ai.daily_budget_usd', ${q(JSON.stringify(5))})`,
  ].join(',\n') + ';'
);
w('');
w('-- end of seed');

writeFileSync('sql/02_seed.sql', out.join('\n'), 'utf8');

// sanity: every referenced image must exist on disk
const missing = rows.filter((r) => !existsSync('public/' + r.img));
console.log(`products: ${rows.length}`);
console.log(`categories: ${BRAND_CATS.length} (max ${arch.maxCat})`);
console.log('per-category counts:', JSON.stringify(Object.fromEntries(Object.entries(perCat).map(([k, v]) => [k, v.length]))));
console.log(`variants: ${varRows.length}, product_tags: ${ptRows.length}`);
console.log(`missing images: ${missing.length}${missing.length ? ' -> ' + missing.map((m) => m.img).join(', ') : ''}`);
console.log(`wrote sql/02_seed.sql (${out.join('\n').length} bytes)`);
